function x = lfm()   
hw = phased.LinearFMWaveform(...
'SweepBandwidth',2e10,...
'PulseWidth',1e-8,...
'PRF',1e6,...
'SampleRate',5e11,...
'OutputFormat','Samples','NumPulses',1,...
'SweepInterval','Positive',...
'NumSamples',5e4);

plot(hw);
x = step(hw);
figure;
plot(real(x)); 
title('Waveform output, real part');
xlabel('Samples'); 
ylabel('Amplitude (V)');